### ISSUE TITLE
i18n for built-in strings

### ISSUE THREAD

**Issue by herienseo** [greyivy/OrnithologistsGuild#1]
Hi, This could be a stupid question.I found that I did not find the translation file of the mail in the i18n file, may I ask were I did not find it? I know it was originally in the Mail.cs file, but then I can't translate it.

**Comment by greyivy** [comment]
Hi @herienseo --  I haven't yet set up all of the i18n files. This is high priority on my list of things to do and I'll update this thread when it's complete.

**Comment by herienseo** [comment]
Ok, thank you very much for your answer.  I'm really looking forward to what happens next.

**Comment by greyivy** [comment]
Fixed! See [`i18n/default.json`](https://github.com/greyivy/OrnithologistsGuild/blob/main/OrnithologistsGuild/i18n/default.json).
